INSERT INTO SEQ_TAB VALUES(SEQ_TAB_1.NEXTVAL,'R');
INSERT INTO SEQ_TAB VALUES(SEQ_TAB_1.NEXTVAL,'A');
INSERT INTO SEQ_TAB VALUES(SEQ_TAB_1.NEXTVAL,'S');
INSERT INTO SEQ_TAB VALUES(SEQ_TAB_1.NEXTVAL,'B');
INSERT INTO SEQ_TAB VALUES(SEQ_TAB_1.NEXTVAL,'V');
INSERT INTO SEQ_TAB VALUES(SEQ_TAB_1.NEXTVAL,'Z');
COMMIT;
/
